/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package STRI_manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.*;

/**
 *
 * @author AlphaOumar
 */
public class SupprimerEq extends javax.swing.JFrame {

    /**
     * Creates new form SupprimerEq
     */
    public SupprimerEq() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomEq = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        validerSup = new javax.swing.JButton();
        Annuler = new javax.swing.JButton();
        Eq = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(nomEq);
        nomEq.setBounds(186, 74, 122, 31);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("                      Saisissez le Nom de l'equipement à supprimer");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 460, 26);

        validerSup.setBackground(new java.awt.Color(255, 255, 255));
        validerSup.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        validerSup.setForeground(new java.awt.Color(255, 0, 0));
        validerSup.setText("Valider");
        validerSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerSupActionPerformed(evt);
            }
        });
        getContentPane().add(validerSup);
        validerSup.setBounds(270, 200, 71, 23);

        Annuler.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Annuler.setForeground(new java.awt.Color(255, 0, 0));
        Annuler.setText("Retour");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        getContentPane().add(Annuler);
        Annuler.setBounds(40, 200, 90, 23);

        Eq.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        Eq.setForeground(new java.awt.Color(255, 0, 0));
        Eq.setText("NOM EQUIPEMENT");
        getContentPane().add(Eq);
        Eq.setBounds(47, 81, 101, 15);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(474, 60, 0, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/computer.jpg"))); // NOI18N
        jLabel2.setMinimumSize(new java.awt.Dimension(400, 400));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 300, 230);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 30, 130, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validerSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerSupActionPerformed
        // TODO add your handling code here:
        
       Equipements_1 E; 
        Connection con=null;
	PreparedStatement st=null;
    ResultSet rs=null;
            try
			 {
		        	//Recuperer les valeurs des differents champs de saisie  
		    		String nom=nomEq.getText();
		    	    E = new Equipements_1();
		    	  //Ajout des Attributs de l'objet equipement a ajouter
		    		E.setNomEq(nom);
		    	 //Vider chaque champ de texte pour une quelconque nouvel ajout
		    		nomEq.setText("");
		    	 con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stricom","root","") ;
		    		st= con.prepareStatement("delete from equipements where nomEq=?");

		             st.setString(1,nom);
		             st.executeUpdate();
                             System.out.println (nom);
                             
		    }
			 catch(Exception ex)
			 {
				 System.out.println(ex.getMessage());
			 } 
       
    }//GEN-LAST:event_validerSupActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        STRI retour = new STRI();
        retour.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupprimerEq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupprimerEq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupprimerEq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupprimerEq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupprimerEq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JLabel Eq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomEq;
    private javax.swing.JButton validerSup;
    // End of variables declaration//GEN-END:variables
}
